### ISSUE TITLE
about how to run

### ISSUE THREAD

**Issue by OverDriveMC** [ppplinday/alexnet-armcomputelibrary-android-withoutfc67#1]
博主您好，我在CSDN上看到您的博客,
请问下AlexNet这个该怎么运行,貌似我没看到在哪个地方读取输入文件？
这个AlexNet的权值是不是自动初始化的。。
刚开始看Arm Compute Library，所以想先试个Demo
我现在可以在TK1上编译好了,但是不太确定该怎么运行,
Thanks

**Comment by ppplinday** [comment]
十分抱歉，，一直没有看github，不好意思。这个输入和权重我都直接写在程序中，程序直接读相应的文件，所以没有输入（其实这样子不太好2333333）。 至于运行就要看看那个Arm Compute Library 或者我记得我写了脚本，可以直接跑。十分不好意思这么晚才回复，忙于学业，要爆炸了233333
